const Miody = [
  {
    name: 'Rokitnik',
    mainModalPhoto: '/Domino/Product webp/Miód_z_rokitnikiem_4.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_rokitnikiem_4.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód z rokitnikiem',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód z rokitnikiem to wyjątkowe połączenie słodyczy miodu i intensywnie kwaśno-owocowego smaku rokitnika. Rokitnik jest znany jako superfood o wysokiej zawartości witaminy C, E oraz antyoksydantów, co czyni ten miód doskonałym wsparciem dla układu odpornościowego i skóry. Jego intensywny smak i bogate właściwości zdrowotne sprawiają, że jest idealnym wyborem dla osób poszukujących naturalnego wzmocnienia organizmu.',
    realization: 'Miód z rokitnikiem powstaje przez dodanie liofilizowanych owoców rokitnika do naturalnego miodu. Liofilizacja zachowuje większość wartości odżywczych rokitnika, w tym witaminy i antyoksydanty, które wzbogacają właściwości zdrowotne miodu. Całość jest dokładnie mieszana, aby uzyskać równomierny rozkład owoców i harmonijne połączenie smaków.',
    properties: [
      'Bogaty w witaminę C, co wspomaga odporność i zdrowie skóry',
      'Wspiera układ sercowo-naczyniowy, pomagając w obniżeniu cholesterolu',
      'Zawiera antyoksydanty, które chronią komórki przed stresem oksydacyjnym',
      'Pomaga w regeneracji skóry i wspiera zdrowy wygląd',
      'Ma właściwości przeciwzapalne, wspierając zdrowie układu pokarmowego',
      'Idealny jako dodatek do herbaty i koktajli, nadając im owocowy, kwaskowaty smak',
    ],
  },
  {
    name: 'Truskawa',
    mainModalPhoto: '/Domino/Product webp/Miód_z_truskawką_5.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_truskawką_5.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód z truskawką',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód z dodatkiem truskawki to słodkie i aromatyczne połączenie, które zachwyca swoim owocowym smakiem i delikatnym aromatem. Truskawki, znane z wysokiej zawartości witaminy C i antyoksydantów, wzbogacają miód o dodatkowe właściwości zdrowotne i nadają mu wyjątkowy smak. Jest to doskonały wybór jako słodki dodatek do deserów, jogurtów, czy też do smarowania pieczywa.',
    realization: 'Miód z truskawką powstaje przez dodanie liofilizowanych truskawek do naturalnego miodu. Liofilizacja pozwala zachować witaminy i składniki odżywcze truskawek, co podkreśla ich walory zdrowotne. Składniki są dokładnie mieszane, aby uzyskać równomierne rozłożenie owoców w miodzie i idealnie zbalansowany smak.',
    properties: [
      'Bogaty w witaminę C, wspierającą odporność i zdrowie skóry',
      'Zawiera antyoksydanty, które pomagają chronić komórki przed starzeniem',
      'Wspomaga zdrowie serca, pomagając obniżać poziom cholesterolu',
      'Działa łagodnie na układ trawienny, wspierając zdrowie żołądka',
      'Naturalny dodatek do deserów, jogurtów i herbat, nadający im słodki, owocowy smak',
      'Może wspierać regenerację skóry dzięki obecności witamin i minerałów',
    ],
  },
  {
    name: 'Gryczany',
    mainModalPhoto: '/Domino/Product webp/Gryczany_11_11zon.webp',
    morePhotos: ['/Domino/Product webp/Gryczany_11_11zon.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód gryczany',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód gryczany ma intensywny, wyrazisty smak oraz charakterystyczny, ciemny kolor. Wyróżnia się wysoką zawartością minerałów, zwłaszcza żelaza, co sprawia, że jest szczególnie polecany osobom z anemią lub osłabieniem organizmu. Jego smak jest nieco ostry i lekko piekący, dzięki czemu stanowi świetny dodatek do dań o intensywnym smaku.',
    realization: 'Miód gryczany pozyskiwany jest z kwiatów gryki, które pszczoły odwiedzają głównie latem, w okresie ich kwitnienia. Kwiaty gryki mają specyficzny, mocny aromat, który przechodzi także do miodu. Po zebraniu nektaru przez pszczoły i przerobieniu go w ulu, miód gryczany jest odparowywany i dojrzewa, co nadaje mu bogaty, intensywny smak.',
    properties: [
      'Bogaty w minerały, zwłaszcza żelazo, co wspiera osoby z anemią',
      'Wzmacnia układ odpornościowy dzięki wysokiej zawartości antyoksydantów',
      'Pomaga obniżać ciśnienie krwi i wspiera układ sercowo-naczyniowy',
      'Przyspiesza gojenie ran i regenerację organizmu',
      'Wspiera zdrowie kości, zębów i skóry dzięki zawartości minerałów',
      'Działa antybakteryjnie i wspiera układ oddechowy w walce z infekcjami',
    ],
  },
  {
    name: 'Akacja',
    mainModalPhoto: '/Domino/Product webp/Miód_akacjowy_18.webp',
    morePhotos: ['/Domino/Product webp/Miód_akacjowy_18.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód akacjowy',
    type: 'akacjowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód akacjowy to jeden z najjaśniejszych rodzajów miodu, często niemal przezroczysty, o delikatnym, łagodnym smaku i subtelnym aromacie kwiatów akacji. Dzięki wysokiej zawartości fruktozy miód ten długo pozostaje w stanie płynnym, nie ulegając szybkiemu krystalizowaniu. Jest szczególnie polecany osobom, które dopiero zaczynają swoją przygodę z miodami, ze względu na jego lekkość i łagodność.',
    realization: 'Miód akacjowy pozyskiwany jest z nektaru kwiatów robinii akacjowej, znanej także jako akacja biała. Pszczoły zbierają nektar w okresie kwitnienia akacji, który przypada na późną wiosnę. Po zebraniu nektaru pszczoły przerabiają go w ulach, odparowując wodę i wzbogacając w enzymy, a następnie przechowują w plastrach miodowych, gdzie miód dojrzewa do momentu, kiedy jest gotowy do pobrania przez pszczelarza.',
    properties: [
      'Wspomaga układ trawienny, łagodząc dolegliwości żołądkowe',
      'Ma właściwości przeciwbakteryjne i wzmacnia odporność',
      'Pomaga regulować poziom cukru we krwi, dzięki czemu jest polecany diabetykom w umiarkowanych ilościach',
      'Działa kojąco na układ nerwowy, pomagając redukować stres i napięcie',
      'Jest łagodny dla żołądka, więc może być stosowany przez osoby z nadkwasotą',
      'Idealnie nadaje się do słodzenia herbaty, jogurtów, czy deserów, nie zmieniając smaku potraw',
    ],
  },
  {
    name: 'Bez',
    mainModalPhoto: '/Domino/Product webp/Miód_bez_19.webp',
    morePhotos: ['/Domino/Product webp/Miód_bez_19.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód z bzem',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód z dodatkiem czarnego bzu to unikalne połączenie klasycznego smaku miodu z intensywnym, lekko kwaskowatym aromatem owoców czarnego bzu. Czarny bez jest znany ze swoich właściwości zdrowotnych, zwłaszcza wspierających odporność, co czyni ten miód doskonałym wyborem w okresie jesienno-zimowym. Dodatek owoców bzu w formie liofilizowanej, nadaje miodowi nie tylko wyjątkowy smak, ale także wzbogaca jego wartości odżywcze.',
    realization: 'Miód z bzem powstaje poprzez dodanie liofilizowanych owoców czarnego bzu do naturalnego miodu. Proces liofilizacji pozwala zachować większość wartości odżywczych bzu, w tym witaminę C i antyoksydanty, które w naturalny sposób wzbogacają właściwości miodu. Składniki są starannie mieszane, aby zapewnić równomierny rozkład owoców i idealne połączenie smaków.',
    properties: [
      'Wzmacnia układ odpornościowy, wspierając walkę z infekcjami',
      'Ma właściwości antywirusowe i przeciwbakteryjne, wspierające zdrowie układu oddechowego',
      'Bogaty w antyoksydanty, które pomagają chronić komórki przed stresem oksydacyjnym',
      'Wspiera układ trawienny, łagodząc dolegliwości żołądkowe',
      'Zawiera witaminę C, wspierającą odporność i zdrowie skóry',
      'Łagodny dla gardła, może pomagać w łagodzeniu bólu gardła',
    ],
  },
  {
    name: 'Czarna Malina',
    mainModalPhoto: '/Domino/Product webp/Miód_czarna_malina_1.webp',
    morePhotos: ['/Domino/Product webp/Miód_czarna_malina_1.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód z czarną maliną',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód z dodatkiem czarnej maliny to wyjątkowe połączenie słodkiego smaku miodu i intensywnego, lekko kwaskowatego aromatu czarnych malin. Czarne maliny, znane z wysokiej zawartości antyoksydantów, doskonale uzupełniają naturalne właściwości miodu, dodając mu unikalny smak oraz cenne składniki odżywcze. To idealny wybór dla osób szukających nietypowych smaków i dodatkowego wsparcia zdrowotnego',
    realization: 'Miód z czarną maliną powstaje przez połączenie naturalnego miodu z liofilizowanymi owocami czarnej maliny. Proces liofilizacji zachowuje pełnię wartości odżywczych owoców, w tym witaminy i antyoksydanty, co pozwala wzmocnić właściwości zdrowotne miodu. Po dodaniu owoców mieszanka jest delikatnie łączona, aby uzyskać jednorodną konsystencję i idealny balans smaków.',
    properties: [
      'Bogaty w antyoksydanty, które wspierają ochronę komórek przed stresem oksydacyjnym',
      'Wzmacnia układ odpornościowy, pomagając organizmowi w walce z infekcjami',
      'Wspiera zdrowie skóry dzięki zawartości witaminy C i innych składników odżywczych',
      'Pomaga obniżać ciśnienie krwi i wspiera zdrowie układu sercowo-naczyniowego',
      'Działa łagodząco na gardło, co może być przydatne przy infekcjach dróg oddechowych',
      'Idealny jako dodatek do napojów, deserów, czy jogurtów, wzbogacając je o naturalny, owocowy smak',
    ],
  },
  {
    name: 'Pigwa',
    mainModalPhoto: '/Domino/Product webp/Miód_z_pigwowcem_3.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_pigwowcem_3.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód z pigwowcem',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód z dodatkiem pigwowca to aromatyczne połączenie klasycznej słodyczy miodu i kwaskowatego, świeżego smaku owoców pigwowca. Pigwowiec jest bogaty w witaminę C oraz składniki wspierające odporność, co czyni ten miód doskonałym wyborem na chłodniejsze dni i jako naturalne wsparcie zdrowia. To idealny dodatek do herbaty, deserów lub jako zdrowa przekąska sama w sobie.',
    realization: 'Miód z pigwowcem powstaje przez dodanie liofilizowanych owoców pigwowca do naturalnego miodu. Proces liofilizacji pozwala zachować witaminy i minerały zawarte w owocach, co wzbogaca miód o dodatkowe właściwości zdrowotne i podkreśla jego smak. Składniki są dokładnie mieszane, aby uzyskać równomierne rozłożenie owoców i idealne połączenie smakowe.',
    properties: [
      'Bogaty w witaminę C, wspomaga układ odpornościowy',
      'Wspiera zdrowie skóry dzięki zawartości antyoksydantów',
      'Pomaga w łagodzeniu przeziębień i infekcji dróg oddechowych',
      'Reguluje trawienie, pomagając przy dolegliwościach żołądkowych',
      'Działa odświeżająco i może wspierać zdrowie jamy ustnej',
      'Idealny dodatek do herbaty, wzbogacający napoje i desery o naturalny, kwaskowaty smak',
    ],
  },
  {
    name: 'Żurawina',
    mainModalPhoto: '/Domino/Product webp/Miód_z_żurawiną_6.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_żurawiną_6.webp', '/Domino/Product webp/work_in_progress.webp'],
    honey_name: 'Miód z żurawiną',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód z dodatkiem żurawiny to harmonijne połączenie słodyczy miodu i kwaśnego, lekko cierpkiego smaku żurawiny. Żurawina jest znana ze swoich właściwości prozdrowotnych, szczególnie wspierających zdrowie układu moczowego oraz odporność. Ten miód to doskonały wybór dla osób szukających naturalnego wsparcia zdrowotnego i lubiących nietypowe, owocowe smaki.',
    realization: 'Miód z żurawiną powstaje przez połączenie naturalnego miodu z liofilizowaną żurawiną. Proces liofilizacji pozwala zachować witaminy, minerały i antyoksydanty zawarte w żurawinie, wzbogacając właściwości zdrowotne miodu. Składniki są dokładnie mieszane, aby uzyskać równomierny rozkład żurawiny i zbalansowany smak.',
    properties: [
      'Wspiera zdrowie układu moczowego, pomagając w profilaktyce infekcji',
      'Bogaty w antyoksydanty, wspomaga ochronę komórek przed stresem oksydacyjnym',
      'Pomaga wzmacniać odporność dzięki wysokiej zawartości witaminy C',
      'Ma działanie przeciwbakteryjne, wspierając zdrowie jamy ustnej',
      'Reguluje trawienie, pomagając przy problemach żołądkowych',
      'Idealny dodatek do herbat, koktajli i deserów, wzbogacający je o kwaskowaty, owocowy smak',
    ],
  },
  {
    name: 'maść',
    mainModalPhoto: '/Domino/Product webp/maść_13.webp',
    morePhotos: ['/Domino/Product webp/maść_13.webp', '/Domino/Product webp/maść-piramida_14'],
    honey_name: 'Maść z propolisem',
  },
];

export default Miody;
