const Miody = [
  {
    name: 'Lotos',
    lampOnSrc: 'LotosOn',
    lampOffSrc: '/LotosOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/LotosOn.jpg', '/LotosOff.jpg'],
    honey_name: 'Miód lipowy',
    type: 'lipowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód lipowy charakteryzuje się intensywnym aromatem kwiatów lipy i delikatną słodyczą. Znany ze swoich właściwości łagodzących kaszel i wspomagających układ odpornościowy.',
    relization: 'Powstaje z nektaru kwiatów lipy, zbierany w okresie kwitnienia drzew, zazwyczaj w lipcu.',
  },
  {
    name: 'Lotos',
    lampOnSrc: 'LotosOn',
    lampOffSrc: '/LotosOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/LotosOn.jpg', '/LotosOff.jpg'],
    honey_name: 'Miód wielokwiatowy',
    type: 'wielokwiatowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód wielokwiatowy to naturalny produkt bogaty w witaminy i minerały, idealny do codziennego użytku. Doskonały jako dodatek do herbaty czy deserów.',
    relization: 'Zbierany z różnych kwiatów polnych i łąkowych, głównie w okresie wiosennym i letnim.',
  },
  {
    name: 'Lotos',
    lampOnSrc: 'LotosOn',
    lampOffSrc: '/LotosOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/LotosOn.jpg', '/LotosOff.jpg'],
    honey_name: 'Miód gryczany',
    type: 'gryczany',
    grammar: '1000g',
    prize: '100zł',
    description: 'Charakterystyczny ciemny kolor i intensywny smak miodu gryczanego sprawiają, że jest ceniony przez osoby dbające o zdrowie. Posiada właściwości wzmacniające i oczyszczające.',
    relization: 'Powstaje z nektaru kwiatów gryki, zbierany w okresie kwitnienia od lipca do sierpnia.',
  },
  {
    name: 'Klucz',
    lampOnSrc: 'KluczOn',
    lampOffSrc: '/KluczOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/KluczOn.jpg', '/KluczOff.jpg'],
    honey_name: 'Miód akacjowy',
    type: 'akacjowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Delikatny i słodki miód akacjowy idealnie sprawdza się jako zdrowa alternatywa dla cukru. Polecany dla dzieci i dorosłych ze względu na łagodne działanie.',
    relization: 'Pozyskiwany z nektaru kwiatów akacji, zbierany na przełomie maja i czerwca.',
  },
  {
    name: 'Klucz',
    lampOnSrc: 'KluczOn',
    lampOffSrc: '/KluczOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/KluczOn.jpg', '/KluczOff.jpg'],
    honey_name: 'Miód wrzosowy',
    type: 'wrzosowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód wrzosowy o lekko gorzkawym smaku jest bogaty w enzymy i składniki odżywcze. Znany z właściwości antybakteryjnych i przeciwzapalnych.',
    relization: 'Powstaje z kwiatów wrzosu, zbierany późnym latem, głównie w sierpniu.',
  },
  {
    name: 'Klucz',
    lampOnSrc: 'KluczOn',
    lampOffSrc: '/KluczOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/KluczOn.jpg', '/KluczOff.jpg'],
    honey_name: 'Miód rzepakowy',
    type: 'rzepakowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód rzepakowy to łagodny miód o kremowej konsystencji, doskonały do wypieków i słodzenia napojów. Ma działanie detoksykacyjne.',
    relization: 'Pozyskiwany z kwiatów rzepaku, zbierany wczesną wiosną, głównie w maju.',
  },
  {
    name: 'Pasek',
    lampOnSrc: 'PasekOn',
    lampOffSrc: '/PasekOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/PasekOn.jpg', '/PasekOff.jpg'],
    honey_name: 'Miód spadziowy',
    type: 'spadziowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód spadziowy, o ciemnym zabarwieniu i wyrazistym smaku, jest ceniony za swoje właściwości lecznicze i wzmacniające organizm.',
    relization: 'Tworzony ze spadzi drzew iglastych, zbierany głównie w lesie w okresie lata.',
  },
  {
    name: 'Pasek',
    lampOnSrc: 'PasekOn',
    lampOffSrc: '/PasekOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/PasekOn.jpg', '/PasekOff.jpg'],
    honey_name: 'Miód malinowy',
    type: 'malinowy',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód malinowy to wyjątkowy produkt o subtelnym smaku malin. Idealny do napojów, deserów oraz jako naturalne wsparcie w okresie przeziębień.',
    relization: 'Pozyskiwany z nektaru kwiatów malin, zbierany od czerwca do sierpnia.',
  },
  {
    name: 'Pasek',
    lampOnSrc: 'PasekOn',
    lampOffSrc: '/PasekOff.jpg',
    lamp1: 'KluczOn',
    lamp2: 'KluczOff',
    lamp3: 'PasekOn',
    morePhotos: ['/PasekOn.jpg', '/PasekOff.jpg'],
    honey_name: 'Miód manuka',
    type: 'manuka',
    grammar: '1000g',
    prize: '100zł',
    description: 'Miód manuka pochodzi z Nowej Zelandii i jest znany ze swoich silnych właściwości antybakteryjnych. Świetnie wspomaga układ odpornościowy.',
    relization: 'Pozyskiwany z nektaru kwiatów krzewu manuka, zbierany wiosną w Nowej Zelandii.',
  },
];

export default Miody;
