const Miody = [
  {
    name: 'Gryczany',
    mainModalPhoto: '/Domino/Product webp/Miód_Gryczany_2.webp',
    morePhotos: ['/Domino/Product webp/Miód_Gryczany_2.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód gryczany',
    type: 'honey',
    grammar_for_small: '620g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '55zł',
    description: 'Miód gryczany o wyrazistym smaku i charakterystycznym ciemnym kolorze to prawdziwa bomba odżywcza, bogata w minerały, zwłaszcza żelazo. Polecany osobom z anemią, osłabieniem organizmu lub szukającym naturalnego wsparcia zdrowia. Jego lekko ostry smak doskonale komponuje się z daniami o intensywnym charakterze.',
    realization: 'Pozyskiwany z kwiatów gryki, miód gryczany powstaje latem, gdy pszczoły zbierają aromatyczny nektar. Po przetworzeniu w ulu miód dojrzewa, nabierając intensywnego smaku i właściwości odżywczych. Gotowy produkt odparowuje wodę i zachowuje pełnię naturalnego aromatu gryki.',
    properties: [
      'Wysoka zawartość żelaza wspierająca osoby z anemią',
      'Naturalne antyoksydanty wzmacniające odporność',
      'Wspiera układ sercowo-naczyniowy, pomagając obniżać ciśnienie krwi',
      'Przyspiesza regenerację organizmu i gojenie ran',
      'Działa antybakteryjnie i wspiera zdrowie układu oddechowego',
      'Wzmacnia kości, zęby i skórę dzięki bogactwu minerałów',
    ],
    properties_title: [
      '*Bogaty w żelazo, idealny dla osób z anemią',
      '*Intensywny smak z nutą ostrości',
      '*Naturalne wsparcie odporności i regeneracji',
      '*Idealny dodatek do intensywnych dań',
      '*Pełnia wartości odżywczych z natury',
    ],
  },
  {
    name: 'Akacja',
    mainModalPhoto: '/Domino/Product webp/Miód_akacjowy_18.webp',
    morePhotos: ['/Domino/Product webp/Miód_akacjowy_18.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód akacjowy',
    type: 'honey',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '35zł',
    prize_for_big: '45zł',
    description: 'Jeden z najdelikatniejszych miodów, miód akacjowy wyróżnia się subtelnym aromatem kwiatów akacji i lekkim, łagodnym smakiem. Dzięki wysokiej zawartości fruktozy pozostaje płynny przez długi czas. Idealny dla osób szukających naturalnej słodyczy i łagodnych doznań smakowych.',
    realization: 'Pszczoły zbierają nektar z kwiatów robinii akacjowej w okresie późnej wiosny, przetwarzając go w ulu na delikatny miód. Proces dojrzewania nadaje mu subtelny smak i kremową konsystencję. Gotowy produkt jest odparowywany i pakowany z zachowaniem najwyższej jakości.',
    properties: [
      'Łagodzi dolegliwości żołądkowe i wspiera układ trawienny',
      'Przeciwbakteryjne właściwości wzmacniają odporność',
      'Pomaga regulować poziom cukru we krwi, odpowiedni dla diabetyków',
      'Koi nerwy, redukując stres i napięcie',
      'Naturalnie łagodny dla żołądka, idealny dla osób z nadkwasotą',
      'Świetny dodatek do herbat, jogurtów i deserów',
    ],
    properties_title: [
      '*Delikatny smak i aromat kwiatów akacji',
      '*Długo pozostaje płynny dzięki wysokiej zawartości fruktozy',
      '*Wspiera odporność i koi układ nerwowy',
      '*Idealny dla diabetyków w umiarkowanych ilościach',
      '*Naturalny wybór dla zdrowia i smaku',
    ],
  },
  {
    name: 'Faceliowy',
    mainModalPhoto: '/Domino/Product webp/Gryczany_11_11zon.webp',
    morePhotos: ['/Domino/Product webp/Gryczany_11_11zon.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód Faceliowy',
    type: 'honey',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '35zł',
    prize_for_big: '45zł',
    description: 'Miód faceliowy to delikatny miód o jasnej barwie i subtelnym, kwiatowym aromacie. Dzięki łagodnemu smakowi idealnie nadaje się zarówno do codziennego użytku, jak i jako składnik deserów. Bogaty w składniki odżywcze, wspiera zdrowie i dodaje energii.',
    realization: 'Pozyskiwany z kwiatów facelii, miód ten jest wynikiem starannej pracy pszczół w okresie kwitnienia roślin. Po zebraniu nektaru miód dojrzewa w ulach, zyskując charakterystyczny delikatny smak. Gotowy produkt zachowuje pełnię naturalnych właściwości i aromatów.',
    properties: [
      'Wzmacnia odporność i dodaje energii',
      'Bogaty w witaminy i minerały wspierające zdrowie',
      'Łagodny smak i aromat idealny dla dzieci i dorosłych',
      'Działa kojąco na układ nerwowy',
      'Wspiera zdrowy styl życia i naturalną regenerację organizmu',
      'Doskonały dodatek do herbaty, deserów i wypieków',
    ],
    properties_title: [
      '*Subtelny, kwiatowy aromat facelii',
      '*Delikatny smak idealny dla całej rodziny',
      '*Naturalna regeneracja i wsparcie zdrowia',
      '*Bogactwo witamin i minerałów',
      '*Wielozadaniowy miód do kuchni i zdrowia',
    ],
  },
  {
    name: 'Wielokwiatowy',
    mainModalPhoto: '/Domino/Product webp/Miód_akacjowy_18.webp',
    morePhotos: ['/Domino/Product webp/Miód_akacjowy_18.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód wielokwiatowy',
    type: 'honey',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '35zł',
    prize_for_big: '45zł',
    description: 'Miód wielokwiatowy to uniwersalny, naturalny miód o delikatnym, kwiatowym smaku i jasnej barwie. Dzięki bogactwu nektarów z różnych roślin jest niezwykle odżywczy i wspiera odporność. To doskonały wybór dla całej rodziny – idealny do herbaty, deserów czy kanapek.',
    realization: 'Miód wielokwiatowy powstaje z nektarów kwiatów zbieranych przez pszczoły w okresie ich największego rozkwitu. Po przetworzeniu w ulu miód dojrzewa, nabierając pełni smaku i aromatu. Gotowy produkt jest starannie pakowany, by zachować jego naturalne właściwości.',
    properties: [
      'Uniwersalny miód o delikatnym kwiatowym smaku',
      'Naturalne wsparcie odporności każdego dnia',
      'Doskonały wybór dla dzieci i dorosłych',
      'Idealny jako dodatek do herbat, deserów i wypieków',
      'Bogaty w składniki odżywcze wspierające zdrowie',
    ],
    properties_title: [
      '*Uniwersalny smak idealny na co dzień',
      '*Naturalne wsparcie odporności i zdrowia',
      '*Delikatny i przyjazny dla dzieci',
      '*Świetny do deserów, herbat i kanapek',
      '*Łagodny aromat i lekka konsystencja',
    ],
  },
  {
    name: 'Rzepakowy',
    mainModalPhoto: '/Domino/Product webp/rzepak.webp',
    morePhotos: ['/Domino/Product webp/rzepak.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód rzepakowy',
    type: 'honey',
    grammar_for_small: '660g',
    grammar_for_big: '1250g',
    prize_for_small: '30zł',
    prize_for_big: '42zł',
    description: 'Miód rzepakowy to łagodny miód o jasnej, kremowej konsystencji i delikatnym kwiatowym aromacie. Dzięki wysokiej zawartości glukozy jest ceniony za swoje właściwości regeneracyjne i wspierające układ krążenia. Idealny jako naturalny słodzik do herbaty czy deserów.',
    realization: 'Pozyskiwany z kwiatów rzepaku, miód ten zbierany jest w okresie ich kwitnienia na wiosnę. Po przetworzeniu przez pszczoły miód zyskuje kremową konsystencję i charakterystyczny łagodny smak. Gotowy produkt jest filtrowany i starannie pakowany, aby zachować jego naturalne właściwości.',
    properties: [
      'Delikatny, kremowy smak i konsystencja',
      'Naturalne wsparcie układu krążenia',
      'Bogactwo glukozy wspomagające regenerację',
      'Idealny dla dzieci i osób starszych',
      'Świetny jako naturalny słodzik do codziennych potraw',
    ],
    properties_title: [
      '*Kremowa konsystencja, delikatny smak',
      '*Wsparcie układu krążenia i regeneracji',
      '*Łagodny dla dzieci i dorosłych',
      '*Naturalny wybór na co dzień',
      '*Bogactwo zdrowotnych właściwości',
    ],
  },
  {
    name: 'Wrzosowy',
    mainModalPhoto: '/Domino/Product webp/wrzos.webp',
    morePhotos: ['/Domino/Product webp/wrzos.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód wrzosowy',
    type: 'honey',
    grammar_for_small: '610g',
    grammar_for_big: '620g',
    prize_for_small: '45zł',
    prize_for_big: '60zł',
    description: 'Miód wrzosowy to jeden z najrzadszych i najbardziej cenionych miodów, wyróżniający się intensywnym smakiem i kwiatowym aromatem. Jego żelowa konsystencja i bogactwo składników odżywczych czynią go prawdziwym skarbem natury. Polecany dla osób dbających o zdrowie i ceniących wyjątkowy smak.',
    realization: 'Pozyskiwany z nektaru wrzosów, miód ten jest zbierany w okresie późnego lata. Pszczoły przetwarzają nektar w ulu, nadając mu wyjątkową konsystencję i aromat. Gotowy produkt zachowuje wszystkie naturalne właściwości, będąc idealnym wyborem dla miłośników miodów premium.',
    properties: [
      'Unikalny, intensywny smak i aromat wrzosu',
      'Bogaty w antyoksydanty i składniki odżywcze',
      'Rzadka i ceniona odmiana miodu',
      'Żelowa konsystencja idealna do degustacji',
      'Doskonale sprawdza się w herbacie i deserach',
    ],
    properties_title: [
      '*Wyjątkowy smak i aromat wrzosu',
      '*Rzadko spotykana odmiana premium',
      '*Wsparcie zdrowia dzięki antyoksydantom',
      '*Idealny do deserów i wyjątkowych chwil',
      '*Żelowa konsystencja o wysokiej jakości',
    ],
  },
  {
    name: 'Pyłek i Pierzga',
    mainModalPhoto: '/Domino/Product webp/Miód_p_p.webp',
    morePhotos: ['/Domino/Product webp/Miód_p_p.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód z pyłkiem i pierzgą',
    type: 'honey',
    grammar_for_small: '420g',
    grammar_for_big: '420g',
    prize_for_small: '40zł',
    prize_for_big: '40zł',
    description: 'Miód z pyłkiem i pierzgą to unikalne połączenie naturalnego miodu, bogatego w smak i właściwości odżywcze, z pyłkiem pszczelim i pierzgą – składnikami o wysokiej zawartości witamin, minerałów i enzymów. Ten produkt to prawdziwa bomba zdrowotna, wspierająca odporność, zdrowie jelit i regenerację organizmu.',
    realization: 'Naturalny miód bazowy jest wzbogacany pyłkiem pszczelim oraz pierzgą, które są starannie łączone, aby zachować ich wartości odżywcze. Proces mieszania gwarantuje jednolitą konsystencję i harmonijny smak. Gotowy produkt jest pakowany w sposób, który zapewnia świeżość i najwyższą jakość.',
    properties: [
      'Wzmacnia układ odpornościowy dzięki naturalnym składnikom',
      'Wspiera zdrowie jelit i procesy trawienne',
      'Bogaty w witaminy, minerały i enzymy',
      'Pomaga w regeneracji organizmu po wysiłku lub chorobie',
      'Idealny dodatek do zdrowej diety, pełen wartości odżywczych',
    ],
    properties_title: [
      '*Naturalna regeneracja organizmu',
      '*Wsparcie odporności i zdrowia jelit',
      '*Bogactwo witamin i minerałów',
      '*Zdrowy dodatek do codziennej diety',
      '*Wyjątkowy smak i kremowa konsystencja',
    ],
  },

  {
    name: 'Rokitnik',
    mainModalPhoto: '/Domino/Product webp/Miód_z_rokitnikiem_4.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_rokitnikiem_4.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód z rokitnikiem',
    type: 'fruit',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód z rokitnikiem to wyjątkowe połączenie słodyczy miodu i intensywnie kwaśno-owocowego smaku rokitnika. Rokitnik jest znany jako superfood o wysokiej zawartości witaminy C, E oraz antyoksydantów, co czyni ten miód doskonałym wsparciem dla układu odpornościowego i skóry. Jego intensywny smak i bogate właściwości zdrowotne sprawiają, że jest idealnym wyborem dla osób poszukujących naturalnego wzmocnienia organizmu.',
    realization: 'Miód z rokitnikiem powstaje przez dodanie liofilizowanych owoców rokitnika do naturalnego miodu. Liofilizacja zachowuje większość wartości odżywczych rokitnika, w tym witaminy i antyoksydanty, które wzbogacają właściwości zdrowotne miodu. Całość jest dokładnie mieszana, aby uzyskać równomierny rozkład owoców i harmonijne połączenie smaków.',
    properties: [
      'Bogaty w witaminę C, co wspomaga odporność i zdrowie skóry',
      'Wspiera układ sercowo-naczyniowy, pomagając w obniżeniu cholesterolu',
      'Zawiera antyoksydanty, które chronią komórki przed stresem oksydacyjnym',
      'Pomaga w regeneracji skóry i wspiera zdrowy wygląd',
      'Ma właściwości przeciwzapalne, wspierając zdrowie układu pokarmowego',
      'Idealny jako dodatek do herbaty i koktajli, nadając im owocowy, kwaskowaty smak',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },
  {
    name: 'Truskawka',
    mainModalPhoto: '/Domino/Product webp/Miód_z_truskawką_5.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_truskawką_5.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód z truskawką',
    type: 'fruit',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód z dodatkiem truskawki to słodkie i aromatyczne połączenie, które zachwyca swoim owocowym smakiem i delikatnym aromatem. Truskawki, znane z wysokiej zawartości witaminy C i antyoksydantów, wzbogacają miód o dodatkowe właściwości zdrowotne i nadają mu wyjątkowy smak. Jest to doskonały wybór jako słodki dodatek do deserów, jogurtów, czy też do smarowania pieczywa.',
    realization: 'Miód z truskawką powstaje przez dodanie liofilizowanych truskawek do naturalnego miodu. Liofilizacja pozwala zachować witaminy i składniki odżywcze truskawek, co podkreśla ich walory zdrowotne. Składniki są dokładnie mieszane, aby uzyskać równomierne rozłożenie owoców w miodzie i idealnie zbalansowany smak.',
    properties: [
      'Bogaty w witaminę C, wspierającą odporność i zdrowie skóry',
      'Zawiera antyoksydanty, które pomagają chronić komórki przed starzeniem',
      'Wspomaga zdrowie serca, pomagając obniżać poziom cholesterolu',
      'Działa łagodnie na układ trawienny, wspierając zdrowie żołądka',
      'Naturalny dodatek do deserów, jogurtów i herbat, nadający im słodki, owocowy smak',
      'Może wspierać regenerację skóry dzięki obecności witamin i minerałów',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },
  {
    name: 'Czarny Bez',
    mainModalPhoto: '/Domino/Product webp/Miód_bez_19.webp',
    morePhotos: ['/Domino/Product webp/Miód_bez_19.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód z czarnym bzem',
    type: 'fruit',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód z dodatkiem czarnego bzu to unikalne połączenie klasycznego smaku miodu z intensywnym, lekko kwaskowatym aromatem owoców czarnego bzu. Czarny bez jest znany ze swoich właściwości zdrowotnych, zwłaszcza wspierających odporność, co czyni ten miód doskonałym wyborem w okresie jesienno-zimowym. Dodatek owoców bzu w formie liofilizowanej, nadaje miodowi nie tylko wyjątkowy smak, ale także wzbogaca jego wartości odżywcze.',
    realization: 'Miód z bzem powstaje poprzez dodanie liofilizowanych owoców czarnego bzu do naturalnego miodu. Proces liofilizacji pozwala zachować większość wartości odżywczych bzu, w tym witaminę C i antyoksydanty, które w naturalny sposób wzbogacają właściwości miodu. Składniki są starannie mieszane, aby zapewnić równomierny rozkład owoców i idealne połączenie smaków.',
    properties: [
      'Wzmacnia układ odpornościowy, wspierając walkę z infekcjami',
      'Ma właściwości antywirusowe i przeciwbakteryjne, wspierające zdrowie układu oddechowego',
      'Bogaty w antyoksydanty, które pomagają chronić komórki przed stresem oksydacyjnym',
      'Wspiera układ trawienny, łagodząc dolegliwości żołądkowe',
      'Zawiera witaminę C, wspierającą odporność i zdrowie skóry',
      'Łagodny dla gardła, może pomagać w łagodzeniu bólu gardła',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },
  {
    name: 'Czarna Malina',
    mainModalPhoto: '/Domino/Product webp/Miód_czarna_malina_1.webp',
    morePhotos: ['/Domino/Product webp/Miód_czarna_malina_1.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód z czarną maliną',
    type: 'fruit',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód z dodatkiem czarnej maliny to wyjątkowe połączenie słodkiego smaku miodu i intensywnego, lekko kwaskowatego aromatu czarnych malin. Czarne maliny, znane z wysokiej zawartości antyoksydantów, doskonale uzupełniają naturalne właściwości miodu, dodając mu unikalny smak oraz cenne składniki odżywcze. To idealny wybór dla osób szukających nietypowych smaków i dodatkowego wsparcia zdrowotnego',
    realization: 'Miód z czarną maliną powstaje przez połączenie naturalnego miodu z liofilizowanymi owocami czarnej maliny. Proces liofilizacji zachowuje pełnię wartości odżywczych owoców, w tym witaminy i antyoksydanty, co pozwala wzmocnić właściwości zdrowotne miodu. Po dodaniu owoców mieszanka jest delikatnie łączona, aby uzyskać jednorodną konsystencję i idealny balans smaków.',
    properties: [
      'Bogaty w antyoksydanty, które wspierają ochronę komórek przed stresem oksydacyjnym',
      'Wzmacnia układ odpornościowy, pomagając organizmowi w walce z infekcjami',
      'Wspiera zdrowie skóry dzięki zawartości witaminy C i innych składników odżywczych',
      'Pomaga obniżać ciśnienie krwi i wspiera zdrowie układu sercowo-naczyniowego',
      'Działa łagodząco na gardło, co może być przydatne przy infekcjach dróg oddechowych',
      'Idealny jako dodatek do napojów, deserów, czy jogurtów, wzbogacając je o naturalny, owocowy smak',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },
  {
    name: 'Pigwowiec',
    mainModalPhoto: '/Domino/Product webp/Miód_z_pigwowcem_3.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_pigwowcem_3.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód z pigwowcem',
    type: 'fruit',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód z dodatkiem pigwowca to aromatyczne połączenie klasycznej słodyczy miodu i kwaskowatego, świeżego smaku owoców pigwowca. Pigwowiec jest bogaty w witaminę C oraz składniki wspierające odporność, co czyni ten miód doskonałym wyborem na chłodniejsze dni i jako naturalne wsparcie zdrowia. To idealny dodatek do herbaty, deserów lub jako zdrowa przekąska sama w sobie.',
    realization: 'Miód z pigwowcem powstaje przez dodanie liofilizowanych owoców pigwowca do naturalnego miodu. Proces liofilizacji pozwala zachować witaminy i minerały zawarte w owocach, co wzbogaca miód o dodatkowe właściwości zdrowotne i podkreśla jego smak. Składniki są dokładnie mieszane, aby uzyskać równomierne rozłożenie owoców i idealne połączenie smakowe.',
    properties: [
      'Bogaty w witaminę C, wspomaga układ odpornościowy',
      'Wspiera zdrowie skóry dzięki zawartości antyoksydantów',
      'Pomaga w łagodzeniu przeziębień i infekcji dróg oddechowych',
      'Reguluje trawienie, pomagając przy dolegliwościach żołądkowych',
      'Działa odświeżająco i może wspierać zdrowie jamy ustnej',
      'Idealny dodatek do herbaty, wzbogacający napoje i desery o naturalny, kwaskowaty smak',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },
  {
    name: 'Żurawina',
    mainModalPhoto: '/Domino/Product webp/Miód_z_żurawiną_6.webp',
    morePhotos: ['/Domino/Product webp/Miód_z_żurawiną_6.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód z żurawiną',
    type: 'fruit',
    grammar_for_small: '610g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód z dodatkiem żurawiny to harmonijne połączenie słodyczy miodu i kwaśnego, lekko cierpkiego smaku żurawiny. Żurawina jest znana ze swoich właściwości prozdrowotnych, szczególnie wspierających zdrowie układu moczowego oraz odporność. Ten miód to doskonały wybór dla osób szukających naturalnego wsparcia zdrowotnego i lubiących nietypowe, owocowe smaki.',
    realization: 'Miód z żurawiną powstaje przez połączenie naturalnego miodu z liofilizowaną żurawiną. Proces liofilizacji pozwala zachować witaminy, minerały i antyoksydanty zawarte w żurawinie, wzbogacając właściwości zdrowotne miodu. Składniki są dokładnie mieszane, aby uzyskać równomierny rozkład żurawiny i zbalansowany smak.',
    properties: [
      'Wspiera zdrowie układu moczowego, pomagając w profilaktyce infekcji',
      'Bogaty w antyoksydanty, wspomaga ochronę komórek przed stresem oksydacyjnym',
      'Pomaga wzmacniać odporność dzięki wysokiej zawartości witaminy C',
      'Ma działanie przeciwbakteryjne, wspierając zdrowie jamy ustnej',
      'Reguluje trawienie, pomagając przy problemach żołądkowych',
      'Idealny dodatek do herbat, koktajli i deserów, wzbogacający je o kwaskowaty, owocowy smak',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },
  {
    name: 'Imbir',
    mainModalPhoto: '/Domino/Product webp/Imb_pig.webp',
    morePhotos: ['/Domino/Product webp/Imb_pig.webp', '/Domino/Product webp/Imb_pig.webp'],
    honey_name: 'Miód z imbirem i pigwowcem',
    type: 'fruit',
    grammar_for_small: '420g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód z imbirem i pigwowcem to wyjątkowe połączenie naturalnego miodu z pikantnym aromatem imbiru i kwaskowatym smakiem pigwowca. Ten duet nie tylko zachwyca smakiem, ale także wspiera odporność i rozgrzewa w chłodne dni. Idealny dodatek do herbaty, deserów, a nawet jako zdrowa przekąska.',
    realization: 'Miód bazowy łączy się z naturalnym imbirem i liofilizowanym pigwowcem, które wzbogacają jego smak i właściwości zdrowotne. Składniki są dokładnie mieszane, aby uzyskać jednolitą konsystencję i pełnię smaku. Gotowy produkt jest pakowany w słoiczki, które zachowują jego świeżość i aromat.',
    properties: [
      'Naturalny miód z dodatkiem imbiru i pigwowca',
      'Wspiera odporność i działa rozgrzewająco',
      'Bogaty w witaminę C i naturalne antyoksydanty',
      'Idealny do herbaty, jako zdrowa przekąska lub dodatek do potraw',
      'Unikalne połączenie pikantnego i kwaskowatego smaku',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },

  {
    name: 'Kawa',
    mainModalPhoto: '/Domino/Product webp/Kawa.webp',
    morePhotos: ['/Domino/Product webp/Kawa.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Miód do kawy',
    type: 'fruit',
    grammar_for_small: '420g',
    grammar_for_big: '1250g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Miód do kawy z przyprawami korzennymi to wyjątkowa kompozycja naturalnego miodu i aromatycznych przypraw, takich jak cynamon, goździki czy kardamon. Idealnie wzbogaca smak kawy, nadając jej ciepły, korzenny aromat. To doskonała alternatywa dla tradycyjnych słodzików, która jednocześnie dodaje kawie charakteru i naturalnych właściwości zdrowotnych.',
    realization: 'Miód przygotowywany jest na bazie naturalnego miodu pszczelego, do którego dodaje się starannie wyselekcjonowane przyprawy korzenne. Składniki są dokładnie mieszane, aby stworzyć jednolitą konsystencję i pełnię smaku. Gotowy produkt jest pakowany w słoiczki, które zachowują świeżość i aromat.',
    properties: [
      'Naturalny miód wzbogacony przyprawami korzennymi',
      'Idealny dodatek do kawy i herbaty',
      'Wzbogaca smak napojów ciepłym, korzennym aromatem',
      'Naturalne źródło antyoksydantów i energii',
      'Doskonały wybór na chłodne dni i wyjątkowe chwile relaksu',
    ],
    properties_title: [
      '*Naturalna słodycz prosto z pasieki',
      '*Bogactwo witamin i antyoksydantów w każdej łyżeczce',
      '*Idealny wybór dla zdrowia i smaku',
      '*Wspiera odporność i dodaje energii każdego dnia',
      '*Niepowtarzalny aromat i doskonała konsystencja',
    ],
  },

  {
    name: 'Maść z propolisem',
    mainModalPhoto: '/Domino/Product webp/maść_13.webp',
    morePhotos: ['/Domino/Product webp/maść_13.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Maść z propolisem i żywokostem',
    type: 'leki',
    grammar_for_small: '50g',
    grammar_for_big: '1000g',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Maść z żywokostem, propolisem i tłuszczem to naturalny produkt o właściwościach regenerujących, przeciwbólowych i przeciwzapalnych. Idealnie sprawdza się w pielęgnacji skóry suchej, podrażnionej oraz w łagodzeniu bólów mięśniowych i stawowych. Dzięki połączeniu żywokostu i propolisu, maść wspomaga procesy regeneracyjne i łagodzi stany zapalne.',
    realization: 'Maść powstaje z naturalnych składników: żywokostu, propolisu i tłuszczu, które są starannie łączone, by zachować pełnię swoich właściwości. Gotowy produkt trafia do specjalnie dobranych, praktycznych pojemników, które chronią naturalną formułę i zapewniają wygodne użytkowanie.',
    properties: [

      'Działa antybakteryjnie i przeciwzapalnie',
      'Wspiera regenerację skóry i gojenie drobnych ran',
      'Zawiera naturalne flawonoidy i olejki eteryczne',
      'Wzmacnia odporność organizmu',

    ],
    properties_title: [
      '*Naturalna regeneracja skóry i tkanki',
      '*Łagodzenie bólu mięśni i stawów',
      '*Doskonała pielęgnacja suchej i podrażnionej skóry',
      '*Bogata w przeciwzapalne składniki z propolisu i żywokostu',
      '*Wygodna w użyciu dzięki kremowej konsystencji',
    ],
  },
  {
    name: 'Krople',
    mainModalPhoto: '/Domino/Product webp/Krople.webp',
    morePhotos: ['/Domino/Product webp/Krople.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Krople z propolisem',
    type: 'leki',
    grammar_for_small: '50ml',
    grammar_for_big: '1000ml',
    prize_for_small: '40zł',
    prize_for_big: '60zł',
    description: 'Krople z propolisu to naturalny preparat wytwarzany z kitu pszczelego rozpuszczonego w 70% spirytusie. Dzięki wysokiej zawartości aktywnych składników, takich jak flawonoidy i olejki eteryczne, krople te mają działanie antybakteryjne, przeciwzapalne i wspierają procesy regeneracyjne organizmu. Idealny do stosowania zewnętrznego na drobne rany, zmiany skórne lub jako suplement wspierający odporność.',
    realization: 'Propolis jest zbierany z uli, oczyszczany i rozpuszczany w 70% spirytusie, aby uzyskać płynny ekstrakt o wysokiej skuteczności. Proces ten pozwala zachować wszystkie właściwości biologiczne propolisu. Gotowy produkt jest filtrowany i pakowany w wygodne buteleczki z aplikatorem kroplowym.',
    properties: [
      'Działa antybakteryjnie i przeciwzapalnie',
      'Wspiera regenerację skóry i gojenie drobnych ran',
      'Zawiera naturalne flawonoidy i olejki eteryczne',
      'Wzmacnia odporność organizmu',
      'Łatwy w aplikacji dzięki buteleczce z kroplomierzem',
    ],
    properties_title: [
      '*Naturalne wsparcie odporności',
      '*Bogactwo antybakteryjnych i przeciwzapalnych składników',
      '*Łatwe w aplikacji dzięki kroplomierzu',
      '*Idealne do pielęgnacji skóry i gojenia drobnych ran',
      '*Wykonane z najwyższej jakości kitu pszczelego',
    ],
  },
  {
    name: 'Pyłek',
    mainModalPhoto: '/Domino/Product webp/pyłek.webp',
    morePhotos: ['/Domino/Product webp/pyłek.webp', '/Domino/Product webp/pyłek.webp'],
    honey_name: 'Pyłek pszczeli',
    type: 'honey',
    grammar_for_small: '1 figurka',
    grammar_for_big: '300g',
    prize_for_small: '35zł',
    prize_for_big: '35zł',
    description: 'Pyłek pszczeli to naturalny superfood pełen witamin, minerałów i białek. Wzmacnia odporność, poprawia samopoczucie i dodaje energii. Doskonały do spożycia samodzielnie, z jogurtem, koktajlami lub miodem, wspiera zdrowy styl życia i regenerację organizmu.',
    realization: 'Pyłek pszczeli jest zbierany przez pszczoły z kwiatów, a następnie oczyszczany i suszony, aby zachować jego wszystkie wartości odżywcze. Gotowy produkt jest starannie pakowany, aby zapewnić najwyższą jakość i świeżość.',
    properties: [
      'Wzmacnia układ odpornościowy',
      'Bogaty w witaminy z grupy B, aminokwasy i minerały',
      'Dodaje energii i pomaga w walce ze zmęczeniem',
      'Wspiera regenerację organizmu',
      'Idealny jako dodatek do zdrowej diety',
    ],
    properties_title: [
      '*Naturalne wsparcie odporności',
      '*Bogactwo witamin, minerałów i białek',
      '*Wspiera zdrowy styl życia i regenerację',
      '*Dodaje energii na cały dzień',
      '*Idealny jako dodatek do posiłków',
    ],
  },
  {
    name: 'Pierzga',
    mainModalPhoto: '/Domino/Product webp/Pieżga_7.webp',
    morePhotos: ['/Domino/Product webp/Pieżga_7.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Pierzga',
    type: 'honey',
    grammar_for_small: '1 figurka',
    grammar_for_big: '200g',
    prize_for_small: '60zł',
    prize_for_big: '60zł',
    description: 'Pierzga pszczela to wyjątkowy produkt pszczeli o wysokiej zawartości enzymów, probiotyków i składników odżywczych. Wspiera zdrowie jelit, wzmacnia odporność i pomaga w regeneracji organizmu. Idealna dla osób ceniących naturalne rozwiązania wspierające zdrowie.',
    realization: 'Pierzga powstaje z pyłku pszczelego, który pszczoły wzbogacają enzymami i przechowują w plastrach. Po naturalnym procesie fermentacji jest zbierana, oczyszczana i starannie pakowana, aby zachować jej wszystkie właściwości.',
    properties: [
      'Wspiera układ odpornościowy i zdrowie jelit',
      'Zawiera probiotyki i naturalne enzymy',
      'Pomaga w regeneracji organizmu po wysiłku lub chorobie',
      'Bogata w witaminy, minerały i antyoksydanty',
      'Naturalny produkt pszczeli o wszechstronnym zastosowaniu',
    ],
    properties_title: [
      '*Naturalne wsparcie układu odpornościowego',
      '*Probiotyki wspierające zdrowie jelit',
      '*Regeneracja organizmu po wysiłku',
      '*Bogactwo witamin i minerałów',
      '*Idealna dla osób ceniących naturalne produkty',
    ],
  },
  {
    name: 'Świeczka Mikołaj',
    mainModalPhoto: '/Domino/Product webp/Miki_11.webp',
    morePhotos: ['/Domino/Product webp/Miki_11.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Mikołaj',
    type: 'ozdoby',
    grammar_for_small: '1 figurka',
    grammar_for_big: '1000ml',
    prize_for_small: '15zł',
    prize_for_big: '60zł',
    description: 'Ozdoby świąteczne z wosku pszczelego to unikalne, ręcznie wykonane i malowane figurki, które doskonale oddają magię świąt. Wykonane z naturalnego wosku pszczelego, łączą tradycję z nowoczesnym designem. Ich subtelny, miodowy zapach dodaje przytulnej atmosfery każdemu wnętrzu. Każda figurka jest zapakowana w ozdobną torebkę, co czyni ją idealnym wyborem na prezent.',
    realization: 'Figurki są ręcznie odlewane z naturalnego wosku pszczelego, a następnie precyzyjnie malowane, aby nadać im świąteczny charakter. Każdy detal jest starannie dopracowany, co sprawia, że ozdoby są wyjątkowe. Małe figurki mogą być pakowane pojedynczo lub w zestawach, w zależności od preferencji klienta.',
    properties: '',
    properties_title: [
      'Ręcznie malowana świeczka w kształcie Mikołaja to symbol świątecznej tradycji. Wykonana z naturalnego wosku pszczelego, idealnie nadaje się jako dekoracja lub drobny upominek.',
    ],
  },
  {
    name: 'Świeczka Rudolf',
    mainModalPhoto: '/Domino/Product webp/Jeleń_12.webp',
    morePhotos: ['/Domino/Product webp/Jeleń_12.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Rudolf',
    type: 'ozdoby',
    grammar_for_small: '1 figurka',
    grammar_for_big: '1000ml',
    prize_for_small: '15zł',
    prize_for_big: '60zł',
    description: 'Ozdoby świąteczne z wosku pszczelego to unikalne, ręcznie wykonane i malowane figurki, które doskonale oddają magię świąt. Wykonane z naturalnego wosku pszczelego, łączą tradycję z nowoczesnym designem. Ich subtelny, miodowy zapach dodaje przytulnej atmosfery każdemu wnętrzu. Każda figurka jest zapakowana w ozdobną torebkę, co czyni ją idealnym wyborem na prezent.',
    realization: 'Figurki są ręcznie odlewane z naturalnego wosku pszczelego, a następnie precyzyjnie malowane, aby nadać im świąteczny charakter. Każdy detal jest starannie dopracowany, co sprawia, że ozdoby są wyjątkowe. Małe figurki mogą być pakowane pojedynczo lub w zestawach, w zależności od preferencji klienta.',
    properties: '',
    properties_title: [
      'Ręcznie malowana świeczka w kształcie renifera wprowadza świąteczny klimat do każdego wnętrza. Naturalny wosk pszczeli nadaje jej niepowtarzalny zapach',
    ],
  },
  {
    name: 'Zestaw świątecznych świeczek',
    mainModalPhoto: '/Domino/Product webp/Miki_z_ziomem_i_choinka_17_11zon.webp',
    morePhotos: ['/Domino/Product webp/Miki_z_ziomem_i_choinka_17_11zon.webp', '/Domino/Product webp/placeholder.webp'],
    honey_name: 'Święta',
    type: 'ozdoby',
    grammar_for_small: '3 figurki',
    grammar_for_big: '1000ml',
    prize_for_small: '60zł',
    prize_for_big: '60zł',
    description: 'Ozdoby świąteczne z wosku pszczelego to unikalne, ręcznie wykonane i malowane figurki, które doskonale oddają magię świąt. Wykonane z naturalnego wosku pszczelego, łączą tradycję z nowoczesnym designem. Ich subtelny, miodowy zapach dodaje przytulnej atmosfery każdemu wnętrzu. Każda figurka jest zapakowana w ozdobną torebkę, co czyni ją idealnym wyborem na prezent.',
    realization: 'Figurki są ręcznie odlewane z naturalnego wosku pszczelego, a następnie precyzyjnie malowane, aby nadać im świąteczny charakter. Każdy detal jest starannie dopracowany, co sprawia, że ozdoby są wyjątkowe. Małe figurki mogą być pakowane pojedynczo lub w zestawach, w zależności od preferencji klienta.',
    properties: '',
    properties_title: [
      'Pełny zestaw świątecznych świeczek: Mikołaj, Renifer i Choinka to dekoracja, która wprowadzi magię świąt do Twojego domu. Wykonane z naturalnego wosku pszczelego i ręcznie malowane, są idealnym wyborem na prezent.',
    ],
  },
  {
    name: 'Biegun południowy',
    mainModalPhoto: '/Domino/Product webp/Miki_z_zimalem_16_11zon.webp',
    morePhotos: ['/Domino/Product webp/Miki_z_zimalem_16_11zon.webp', '/Domino/Product webp/Miki_z_zimalem_16_11zon.webp'],
    honey_name: 'Drużyna',
    type: 'ozdoby',
    grammar_for_small: '2 figurki',
    grammar_for_big: '1000ml',
    prize_for_small: '30zł',
    prize_for_big: '60zł',
    description: 'Ozdoby świąteczne z wosku pszczelego to unikalne, ręcznie wykonane i malowane figurki, które doskonale oddają magię świąt. Wykonane z naturalnego wosku pszczelego, łączą tradycję z nowoczesnym designem. Ich subtelny, miodowy zapach dodaje przytulnej atmosfery każdemu wnętrzu. Każda figurka jest zapakowana w ozdobną torebkę, co czyni ją idealnym wyborem na prezent.',
    realization: 'Figurki są ręcznie odlewane z naturalnego wosku pszczelego, a następnie precyzyjnie malowane, aby nadać im świąteczny charakter. Każdy detal jest starannie dopracowany, co sprawia, że ozdoby są wyjątkowe. Małe figurki mogą być pakowane pojedynczo lub w zestawach, w zależności od preferencji klienta.',
    properties: '',
    properties_title: [
      'Świąteczny zestaw świeczek w kształcie Mikołaja i Renifera to idealna dekoracja na święta. Wykonane z naturalnego wosku pszczelego i ręcznie malowane, są doskonałym pomysłem na prezent.',
    ],
  },
  {
    name: 'Zestaw prezentowy 1',
    mainModalPhoto: '/Domino/Product webp/prezenty-3_10_11zon.webp',
    morePhotos: ['/Domino/Product webp/prezenty-3_10_11zon.webp', '/Domino/Product webp/prezenty-3_10_11zon.webp'],
    honey_name: 'Zestaw prezentowy 1',
    type: 'zestaw',
    grammar_for_small: '6 produktów w zestawie',
    grammar_for_big: 'Kliknij po wiecej szczegółów',
    prize_for_small: '60zł',
    prize_for_big: '60zł',
    description: '',
    realization: '',
    properties: [''],
    properties_title: [
      'W skład zestawu wchodzą:',
      '1 świeczka w kształcie Mikołaja',
      '1 świeczka w kształcie Renifera',
      '4 miody smakowe (50g) w różnych, unikalnych smakach',
      'Ten wyjątkowy zestaw to idealne połączenie świątecznej dekoracji i naturalnych, słodkich smaków. Doskonały jako prezent na każdą okazję, który zachwyci zarówno miłośników estetycznych ozdób, jak i smakoszy miodu.',
    ],
  },
  {
    name: 'Zestaw prezentowy 2',
    mainModalPhoto: '/Domino/Product webp/prezenty-2_9_11zon.webp',
    morePhotos: ['/Domino/Product webp/prezenty-2_9_11zon.webp', '/Domino/Product webp/prezenty-2_9_11zon.webp'],
    honey_name: 'Zestaw prezentowy 2',
    type: 'zestaw',
    grammar_for_small: '6 produktów w zestawie',
    grammar_for_big: 'Kliknij po wiecej szczegółów',
    prize_for_small: '110zł',
    prize_for_big: '60zł',
    description: '',
    realization: '',
    properties: [''],
    properties_title: [
      'W skład zestawu wchodzą:',
      'Krople propolisowe (naturalny ekstrakt propolisu w 70% spirytusie)',
      'Maść z żywokostem i propolisem',
      '4 miody smakowe (50g) w różnych, unikalnych smakach',
      'Zestaw łączy naturalne produkty pszczele o właściwościach zdrowotnych i smakowych. To idealny wybór na prezent dla osób ceniących naturę, zdrowie i wyjątkowe doznania smakowe. Eleganckie opakowanie sprawia, że jest to doskonały upominek na każdą okazję.',
    ],
  },
  {
    name: 'Miód pitny',
    mainModalPhoto: '/Domino/Product webp/Wóda.webp',
    morePhotos: ['/Domino/Product webp/Wóda.webp', '/Domino/Product webp/Wóda.webp'],
    honey_name: 'Miód pitny',
    type: 'alkohol',
    grammar_for_small: '500ml',
    grammar_for_big: '700ml',
    prize_for_small: '45zł',
    prize_for_big: '45zł',
    description: 'Miód pitny to 12% tradycyjny napój alkoholowy wytwarzany z naturalnego miodu pszczelego, wody i dodatków, takich jak owoce czy przyprawy. Jego korzenie sięgają starożytności, gdzie był symbolem luksusu i wyjątkowych okazji. W zależności od proporcji składników, miód pitny może być słodki, półsłodki lub wytrawny, zachwycając głębią smaku i aromatu.',
    realization: 'Miód pitny powstaje poprzez fermentację naturalnego miodu pszczelego z wodą, z dodatkiem drożdży, które przekształcają cukry w alkohol. W trakcie produkcji można dodawać owoce, przyprawy lub zioła, które wzbogacają smak i aromat. Proces dojrzewania trwa od kilku miesięcy do kilku lat, co pozwala na rozwinięcie pełnego bukietu smaku. Gotowy miód pitny jest butelkowany i gotowy do spożycia lub dalszego starzenia.',
    properties: [
      'Naturalnie fermentowany napój z wysokiej jakości miodu',
      'Bogaty smak z unikalnymi nutami owoców i przypraw',
      'Idealny do celebracji oraz wieczorów przy dobrym towarzystwie',
      'Źródło naturalnych antyoksydantów z miodu',
      'Możliwość wyboru między słodkim, półsłodkim i wytrawnym smakiem',
    ],
    properties_title: [
      '*Tradycyjny napój o bogatej historii',
      '*Naturalnie fermentowany z najwyższej jakości miodu',
      '*Wyjątkowy smak z nutą słodyczy i głębi',
      '*Idealny do celebracji i wyjątkowych okazji',
      '*Wspiera naturalną odporność dzięki właściwościom miodu',
    ],
  },
];

export default Miody;
